### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
POST {{url}}/todos/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/todos
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/todos/mine
Accept: application/json
Authorization: Bearer {{jwt_token}}


###
GET {{url}}/todos/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
POST {{url}}/todos
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "title": "New Todo",
    "description": "New Todo Description"
}

###
PUT {{url}}/todos/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "title": "Updated Todo",
    "description": "Updated Todo Description"
}

###
DELETE {{url}}/todos/1
Authorization: Bearer {{jwt_token}}

